import argparse
import os.path
import types

parser = argparse.ArgumentParser(description='File wrapper.')

parser.add_argument("-f", "--file", dest="filename", required=True, help="REQUIRED. input file")
parser.add_argument("-n", "--name", dest="cvarname", help="name of the generated C string variable")

options = parser.parse_args()

inputfile = open(options.filename, "rb")

basename, extension = os.path.splitext(options.filename)
if extension:
	outputfilename = basename + "_" + extension.strip('.') + ".h"
else:
	outputfilename = basename + ".h"

if options.cvarname:
	cvarname = options.cvarname
else:
	(head, tail) = os.path.split(options.filename);
	basetail = os.path.splitext(tail)[0]
	postfix = extension.strip('.')
	if postfix:
		cvarname = "psz" + "_" + basetail + "_" + postfix
	else:
		cvarname = "psz" + "_" + basetail

byline = "//Auto-generated by fwrap.py. Do not edit manually\n";

headerfile = byline + "const unsigned char " + cvarname + " [] = {\n"

headerfile = headerfile;

chars = inputfile.read()

for char in chars:
	headerfile = headerfile + str(ord(char)) + ",\n"

headerfile = headerfile + "};\n"

# register with file system

inputfile.close()
outputfile = open(outputfilename, "w")
outputfile.write(headerfile)
outputfile.close()

